# Đặt tên cho ứng dụng Spring Boot của team
spring.application.name=velora-clock

# ================= KẾT NỐI SQL SERVER =================
# Cấu hình đường dẫn URL đến Database
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=VeloraClockWeb;encrypt=true;trustServerCertificate=true;

# Tài khoản và mật khẩu đăng nhập SQL Server Management Studio (SSMS)
spring.datasource.username=sa
spring.datasource.password=123456

# Khai báo Driver kết nối
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# ================= CẤU HÌNH JPA / HIBERNATE =================
# ĐÃ SỬA LỖI: Đổi từ 'update' thành 'none' để Hibernate KHÔNG ĐƯỢC CHỌC NGOÁY vào cấu trúc bảng SQL Server của em nữa
spring.jpa.hibernate.ddl-auto=none

# Hiển thị các câu lệnh SQL chạy ngầm lên Console để dễ debug lỗi
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Định nghĩa loại DB đang dùng để Hibernate tối ưu câu lệnh
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

#============================== GỬI EMAIL TỰ ĐỘNG ======================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=phamkhoi2746@gmail.com
# Mật khẩu ứng dụng (App Password)
spring.mail.password=kgzhqkmcdbshesvi
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true